name: Makefile CI

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}  
        
    - name: Install dependencies
      run: make
     
    - name: Package deb file
      run: VERSION=1.0.0 make package-deb
      
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
