name: Makefile CI

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Install dependencies
      run: make
     
    - name: Package deb file
      run: VERSION=1.0.${{ github.run_number }} make package-deb

    - name: Output Run Number
      run: echo 1.0.${{ github.run_number }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: prompt_1.0.${{ github.run_number }}.deb
        path: package
        if-no-files-found: error
        retention-days: 90
